version: '3.7'
services:
    express:
        container_name: server-side-graph-ql
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        volumes:
            - ./server:/usr/src/99-backend
        command: yarn run app
        ports:
            - "4000:4000"
        networks:
            - graph
    react:
        container_name: client-side-graph-ql
        stdin_open: true
        build:
            context: ./
            dockerfile: ./client/Dockerfile
        volumes:
            - ./client:/usr/src/99-frontend
        command: yarn start
        ports:
            - "3000:3000"
        networks:
            - graph

volumes:
    database:

networks:
    graph:
        driver: bridge