version: '3.7'
services:
    database:
        container_name: database
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - database:/data/db
        networks:
            - graph

volumes:
    database:

networks:
    graph:
        driver: bridge